<section xml:id="references-exceptions_vocabulary"
         xmlns:xi="http://www.w3.org/2001/XInclude">
  <title>Vocabulary</title>
  <p>
    <dl>
      <li>
        <title>reference:</title>
        <p>
          <idx>
            <h>reference</h>
          </idx> A variable that <q>points to</q> the storage location of another variable.</p>
      </li>
      <li>
        <title>alias:</title>
        <p>
          <idx>
            <h>alias</h>
          </idx> A variable that is essentially another name for some other variable.</p>
      </li>
      <li>
        <title>high-level code:</title>
        <p>
          <idx>
            <h>high-level code</h>
          </idx> Code that is responsible for the big picture. A relative term. A given function is higher level than functions it calls and is lower level than functions that call it.</p>
      </li>
      <li>
        <title>low-level code:</title>
        <p>
          <idx>
            <h>low-level code</h>
          </idx> Code that is responsible for small details. A relative term. A given function is higher level than functions it calls and is lower level than functions that call it.</p>
      </li>
      <li>
        <title>exception:</title>
        <p>
          <idx>
            <h>exception</h>
          </idx> A message indicating that a function encountered an error that prevented it from completing.</p>
      </li>
      <li>
        <title>throw:</title>
        <p>
          <idx>
            <h>throw</h>
          </idx> When a function produces an exception, we say it throws the exception. </p>
      </li>
      <li>
        <title>try:</title>
        <p>
          <idx>
            <h>try</h>
          </idx> Starts a block of code where we are going to try to contain any exceptions that happen.</p>
      </li>
      <li>
        <title>catch:</title>
        <p>
          <idx>
            <h>catch</h>
          </idx> A statement attached to a <pf>try</pf> that handles a particular type of exception.</p>
      </li>
      <li>
        <title>propagate:</title>
        <p>
          <idx>
            <h>propagate</h>
          </idx> What happens when a function fails to <pf>catch</pf> an exception - it is passed up to the next higher function in the call stack.</p>
      </li>
    </dl>
  </p>
</section>